### ISSUE TITLE
Can't import npytools after pip install in conda env

### ISSUE THREAD

**Issue by TomBugnon** [cortex-lab/npytools#1]
Hi, 
I installed npytools in a python 3.7.7 conda environment on ubuntu 20.04 with 
`pip install git+https://github.com/cortex-lab/npytools.git`

`pip show npytools` returns:
> Name: npytools
> Version: 0.1.0
> Summary: Command-line utilities for the NumPy file format
> Home-page: https://github.com/cortex-lab/npytools
> Author: Cyrille Rossant (cortex-lab/UCL/IBL)
> Author-email: cyrille.rossant at gmail.com
> License: BSD
> Location: /Volumes/scratch/neuropixels/miniconda3/envs/neuropix/lib/python3.7/site-packages
> Requires:
> Required-by:

And the binary npyshow is on path.

However I can't import the package, either with a direct import from python or when running npyshow:
`npyshow --help`
> Traceback (most recent call last):
>   File "/Volumes/scratch/neuropixels/miniconda3/envs/neuropix/bin/npyshow", line 5, in <module>
>     from npytools import npyshow
> ModuleNotFoundError: No module named 'npytools'

Any idea what might be going on? 
Best, Tom

**Comment by rossant** [comment]
Could you double-check that the `pip` executable that you used to install npytools is from the same Python environment than your neuropix conda environment?

**Comment by TomBugnon** [comment]
Thks for your response. It is. To double check I reinstalled npytools with `python -m pip install git+https://github.com/cortex-lab/npytools.git` and the issue remains.

**Comment by rossant** [comment]
- `python -c "import npytools"` fails too?
- what if you clone the repo and do `pip install -e . --upgrade` in it?

**Comment by TomBugnon** [comment]
`python -c "import npytools"` fails as well, but the local installation does solve the issue, thank you!
Let me know if I can do anything more to help you with debugging.
Best

**Comment by aemonge** [comment]
`pipx install` also fails:

```
❯ pipx install git+https://github.com/cortex-lab/npytools.git

  installed package npytools 0.1.0, installed using Python 3.12.6
  These apps are now globally available
    - npyplot
    - npyshow
done! ✨ 🌟 ✨
❯ npyshow validation/simunpy/a/_____.npy
Traceback (most recent call last):
  File "/home/aemonge/.local/bin/npyshow", line 5, in <module>
    from npytools import npyshow
ModuleNotFoundError: No module named 'npytools'

```
